name: Joffrey Kern's Blog
description: My world about development, agile
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://joffreykern.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
permalink: /blog/:title
# permalink: /blog/:year/:month/:day/:title

# Details for the RSS feed generator
url:            'blog url'
author:         'Joffrey Kern'