name: Joffrey Kern
description: My world about C#, development, agile and stuffs...
meta_description: "My world about C#, development, agile and stuffs..."

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://joffreykern.github.io'
google_analytics: 'UA-16213895-4'
gems: [jekyll-paginate]
permalink: /blog/:title
# permalink: /blog/:year/:month/:day/:title

# Details for the RSS feed generator
url:            'blog url'
author:         'Joffrey Kern'